<?php

namespace Database\Seeders;

use App\Models\MitraPerusahaan;
use Illuminate\Database\Seeder;

class MitraPerusahaanSeeder extends Seeder
{
    public function run(): void
    {
        $mitras = [
            [
                'name' => 'PT Telkom Indonesia',
                'slug' => 'pt-telkom-indonesia',
                'short_name' => 'Telkom Indonesia',
                'sector' => 'Teknologi Informasi',
                'city' => 'Surabaya',
                'description' => 'Mitra strategis penyedia tempat magang PKL kejuruan RPL & SIJA dengan supervisi mentor industri.',
                'website' => 'https://www.telkom.co.id',
                'logo_color' => '#dc2626',
                'logo_text' => 'TELKOM',
                'is_mou_active' => true,
                'mou_until' => '2028-12-31',
                'programs' => ['Tempat PKL Resmi', 'Kelas Industri Fiber', 'Guru Tamu & Uji UKK'],
                'stats' => ['siswa_pkl' => 32, 'kelas_industri' => 1, 'peluang_aktif' => 2],
                'address' => 'Plaza Telkom Ketintang Baru, Jl. Ketintang Baru No. 1-3, Gayungan, Surabaya',
                'distance_note' => '±1,8 km dari SMKN 1 Surabaya (6 Menit Perjalanan)',
                'kemitraan_sejak' => 2021,
                'narahubung_nama' => 'Bpk. Aris Santoso, S.Kom',
                'narahubung_jabatan' => 'Pokja PKL & Kemitraan DUDI',
                'narahubung_wa' => '6281234567890',
                'kelas_industri' => [
                    'jurusan_sasaran' => ['RPL', 'TKJ'],
                    'instruktur' => 'Pendampingan 32 JP / Semester',
                    'output_sertifikasi' => 'Sertifikat Telkom DTI',
                ],
                'documents' => [
                    ['name' => 'Silabus_Kelas_Industri_Telkom.pdf', 'desc' => 'Standar Kompetensi PKL (2.4 MB)', 'size' => '2.4 MB', 'url' => '#'],
                    ['name' => 'Tata_Tertib_dan_K3_Praktik_Industri.pdf', 'desc' => 'Pedoman K3 industri (680 KB)', 'size' => '680 KB', 'url' => '#'],
                    ['name' => 'Format_Surat_Izin_Ortu_Telkom.docx', 'desc' => 'Template Pokja PKL (450 KB)', 'size' => '450 KB', 'url' => '#'],
                    ['name' => 'Skema_Uji_Kompetensi_Kejuruan_DTI.pdf', 'desc' => 'Skema UKK DTI (1.1 MB)', 'size' => '1.1 MB', 'url' => '#'],
                ],
            ],
            [
                'name' => 'PT Beon Intermedia',
                'slug' => 'pt-beon-intermedia',
                'short_name' => 'Beon Intermedia',
                'sector' => 'Teknologi Informasi',
                'city' => 'Malang / Surabaya',
                'description' => 'Pengembang ekosistem web hosting dan infrastruktur server cloud, mitra sertifikasi dan kompetisi vokasi.',
                'website' => 'https://www.jagoanhosting.com',
                'logo_color' => '#f97316',
                'logo_text' => 'JAGOAN',
                'is_mou_active' => true,
                'mou_until' => '2027-12-31',
                'programs' => ['Kelas Industri', 'Sponsor JHIC'],
                'stats' => ['siswa_pkl' => 12, 'kelas_industri' => 1, 'peluang_aktif' => 2],
                'address' => 'Jl. Dipati Ukur No. 123, Bandung / Surabaya',
                'distance_note' => '±2,4 km dari SMKN 1 Surabaya (8 Menit Perjalanan)',
                'kemitraan_sejak' => 2022,
                'narahubung_nama' => 'Bpk. Rizal Pratama',
                'narahubung_jabatan' => 'Partnership Manager',
                'narahubung_wa' => '6281298765432',
                'kelas_industri' => [
                    'jurusan_sasaran' => ['RPL', 'SIJA'],
                    'instruktur' => 'Mentoring DevOps 24 JP / Semester',
                    'output_sertifikasi' => 'Sertifikat Cloud Engineer Dasar',
                ],
                'documents' => [
                    ['name' => 'Silabus_DevOps_Jagoan_Hosting.pdf', 'desc' => 'Silabus kelas industri (980 KB)', 'size' => '980 KB', 'url' => '#'],
                    ['name' => 'Panduan_Dokumentasi_Container.pdf', 'desc' => 'Panduan Docker dasar (1.2 MB)', 'size' => '1.2 MB', 'url' => '#'],
                ],
            ],
            [
                'name' => 'PT Bank Jatim Tbk',
                'slug' => 'pt-bank-jatim-tbk',
                'short_name' => 'Bank Jatim',
                'sector' => 'Perbankan & Jasa',
                'city' => 'Surabaya',
                'description' => 'Lembaga perbankan daerah Jawa Timur yang menyerap lulusan akuntansi serta praktikan IT helpdesk.',
                'website' => 'https://www.bankjatim.co.id',
                'logo_color' => '#dc2626',
                'logo_text' => 'B.JATIM',
                'is_mou_active' => true,
                'mou_until' => '2027-06-30',
                'programs' => ['Tempat PKL Resmi', 'Rekrutmen BKK'],
                'stats' => ['siswa_pkl' => 18, 'kelas_industri' => 0, 'peluang_aktif' => 2],
                'address' => 'Jl. Basuki Rahmat No. 98-114, Surabaya',
                'distance_note' => '±2,1 km dari SMKN 1 Surabaya (7 Menit Perjalanan)',
                'kemitraan_sejak' => 2020,
                'narahubung_nama' => 'Ibu Siti Handayani',
                'narahubung_jabatan' => 'Humas & Kemitraan',
                'narahubung_wa' => '6281133445566',
                'kelas_industri' => [
                    'jurusan_sasaran' => ['AKL'],
                    'instruktur' => 'Pendampingan 16 JP / Semester',
                    'output_sertifikasi' => 'Sertifikat Perbankan Dasar',
                ],
                'documents' => [
                    ['name' => 'Surat_Pengantar_PKL_Bank_Jatim.pdf', 'desc' => 'Format pengantar resmi (320 KB)', 'size' => '320 KB', 'url' => '#'],
                    ['name' => 'Panduan_Praktik_IT_Helpdesk.pdf', 'desc' => 'Panduan helpdesk (760 KB)', 'size' => '760 KB', 'url' => '#'],
                ],
            ],
            [
                'name' => 'PT Astra Graphia IT',
                'slug' => 'pt-astra-graphia-it',
                'short_name' => 'Astra Graphia',
                'sector' => 'Teknologi Informasi',
                'city' => 'Surabaya',
                'description' => 'Anak perusahaan Astra Group yang berfokus pada teknologi informasi, penyedia magang pengembang web & infrastruktur.',
                'website' => 'https://www.astragraphia.com',
                'logo_color' => '#f97316',
                'logo_text' => 'ASTRA',
                'is_mou_active' => true,
                'mou_until' => '2028-03-31',
                'programs' => ['Tempat PKL Resmi', 'Rekrutmen BKK'],
                'stats' => ['siswa_pkl' => 15, 'kelas_industri' => 1, 'peluang_aktif' => 2],
                'address' => 'Jl. Pemuda No. 31-37, Surabaya',
                'distance_note' => '±2,6 km dari SMKN 1 Surabaya (9 Menit Perjalanan)',
                'kemitraan_sejak' => 2022,
                'narahubung_nama' => 'Bpk. Dian Kurniawan',
                'narahubung_jabatan' => 'HR & Kemitraan',
                'narahubung_wa' => '6281211112222',
                'kelas_industri' => [
                    'jurusan_sasaran' => ['RPL'],
                    'instruktur' => 'Pendampingan 24 JP / Semester',
                    'output_sertifikasi' => 'Sertifikat Junior Web Developer',
                ],
                'documents' => [
                    ['name' => 'Skema_PKL_Astra_Graphia.pdf', 'desc' => 'Skema PKL (540 KB)', 'size' => '540 KB', 'url' => '#'],
                    ['name' => 'Formulir_Daftar_Ulang_Astra.docx', 'desc' => 'Formulir daftar ulang (210 KB)', 'size' => '210 KB', 'url' => '#'],
                ],
            ],
            [
                'name' => 'PT Maspion Group',
                'slug' => 'pt-maspion-group',
                'short_name' => 'Maspion',
                'sector' => 'Manufaktur & Logistik',
                'city' => 'Surabaya',
                'description' => 'Konglomerasi manufaktur terkemuka yang rutin menyerap alumni jurusan Akuntansi, Administrasi, dan TKJ.',
                'website' => 'https://www.maspion.com',
                'logo_color' => '#2563eb',
                'logo_text' => 'MASPION',
                'is_mou_active' => true,
                'mou_until' => '2027-12-31',
                'programs' => ['Penyalur Alumni', 'Uji Kompetensi'],
                'stats' => ['siswa_pkl' => 10, 'kelas_industri' => 0, 'peluang_aktif' => 1],
                'address' => 'Rungkut Industri III No. 10-18, Surabaya',
                'distance_note' => '±4,2 km dari SMKN 1 Surabaya (12 Menit Perjalanan)',
                'kemitraan_sejak' => 2019,
                'narahubung_nama' => 'Bpk. Bambang Setiawan',
                'narahubung_jabatan' => 'Manajer SDM',
                'narahubung_wa' => '6281277778888',
                'kelas_industri' => [
                    'jurusan_sasaran' => ['AKL', 'BDP'],
                    'instruktur' => 'Pendampingan 12 JP / Semester',
                    'output_sertifikasi' => 'Sertifikat Administrasi Industri',
                ],
                'documents' => [
                    ['name' => 'Panduan_Praktik_Administrasi_Maspion.pdf', 'desc' => 'Panduan administrasi (410 KB)', 'size' => '410 KB', 'url' => '#'],
                    ['name' => 'Jadwal_Rotasi_Departemen_Maspion.xlsx', 'desc' => 'Jadwal rotasi (95 KB)', 'size' => '95 KB', 'url' => '#'],
                ],
            ],
            [
                'name' => 'MNC Media Biro Jatim',
                'slug' => 'mnc-media-biro-jatim',
                'short_name' => 'MNC Media',
                'sector' => 'Kreatif & Media',
                'city' => 'Surabaya',
                'description' => 'Jaringan media penyiaran dan visual pertelevisian nasional yang menjadi lab praktik industri siswa DKV.',
                'website' => 'https://www.mncgroup.com',
                'logo_color' => '#7c3aed',
                'logo_text' => 'MNC',
                'is_mou_active' => true,
                'mou_until' => '2028-01-31',
                'programs' => ['Tempat PKL Resmi', 'Mitra DKV'],
                'stats' => ['siswa_pkl' => 14, 'kelas_industri' => 0, 'peluang_aktif' => 0],
                'address' => 'Jl. Raya Darmo Permai Selatan No. 8, Surabaya',
                'distance_note' => '±3,3 km dari SMKN 1 Surabaya (10 Menit Perjalanan)',
                'kemitraan_sejak' => 2023,
                'narahubung_nama' => 'Ibu Maya Lestari',
                'narahubung_jabatan' => 'Creative Producer',
                'narahubung_wa' => '6281255556666',
                'kelas_industri' => [
                    'jurusan_sasaran' => ['DKV'],
                    'instruktur' => 'Pendampingan 20 JP / Semester',
                    'output_sertifikasi' => 'Sertifikat Production Assistant',
                ],
                'documents' => [
                    ['name' => 'Surat_Kerja_Sama_MNC_Media.docx', 'desc' => 'Draf kerja sama (180 KB)', 'size' => '180 KB', 'url' => '#'],
                    ['name' => 'Panduan_Produksi_Konten_MNC.pdf', 'desc' => 'Panduan produksi (890 KB)', 'size' => '890 KB', 'url' => '#'],
                ],
            ],
        ];

        foreach ($mitras as $mitra) {
            MitraPerusahaan::updateOrCreate(['slug' => $mitra['slug']], $mitra);
        }
    }
}
